### ISSUE TITLE
成本计算问题?

### ISSUE THREAD

**Issue by rikxqd** [rocaltair/lastar#1]
https://github.com/rocaltair/lastar/blob/master/test.lua#L19

这里的成本计算是不是有问题？tx和ty并非最终点的坐标，是fx,fy 周围九格的坐标？应该写为
`local dis = ((tx == fx) or (ty == fy)) and 1 or 1.4` 这样?

**Comment by rocaltair** [comment]
嗯，手误
local dis = (tx - fx) * (ty - fy) > 0 and 1.4 or 1

**Comment by rocaltair** [comment]
@rikxqd A*情况下算出来的都是锯齿状的路径，会很丑。你可以参考一下floyd平滑算法。先去掉线段上的非拐点，再二分法去拐点。最后用bresenham可以拉出比较平滑的折线出来，比较接近人类的行走路线

**Comment by rikxqd** [comment]
@rocaltair 谢谢指点，现在我们的宠物走起来会很丑，但没办法，不可能像你说的那样做那么多的运算啊
